# Generated by Django 3.2.4 on 2021-10-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_useraccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At'),
        ),
    ]
